version: "3.8" 

services:
  backend:
    build:
      context: .  # Main directory (where Dockerfile is located)
      dockerfile: Dockerfile  # Dockerfile located here
    ports:
      - "3389:3389" 
    networks:
      - app-network
    depends_on:
      - postgres  # Wait for the database to be ready before starting the backend

  postgres:
    image: postgres:17  # Use the official PostgreSQL image
    ports:
      - "5432:5432"  # Map the PostgreSQL port to the host machine
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data in a named volume

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:  # Define the named volume for database data
  uploads:  # Define the named volume for image uploads
