version: "3.8"  # or whatever version you're using

services:
  backend:
    build:
      context: .  # Main directory (where Dockerfile is located)
      dockerfile: Dockerfile  # Dockerfile located here
    ports:
      - "3000:3000"  # Map port 3000 inside container to port 3000 on host
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}  # Name of your database service
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    depends_on:
      - postgres  # Wait for the database to be ready before starting the backend

  postgres:
    image: postgres:13  # Use the official PostgreSQL image
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5433:5432"  # Map the PostgreSQL port to the host machine
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data in a named volume

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:  # Define the named volume for database data
  uploads:  # Define the named volume for image uploads
