version: "3.8"  # or whatever version you're using

services:
  backend:
    build:
      context: .  # Main directory (where Dockerfile is located)
      dockerfile: Dockerfile  # Dockerfile located here
    ports:
      - "3000:3000"  # Map port 3000 inside container to port 3000 on host
    networks:
      - app-network
    env_file:
    - .env  # Make sure this points to the correct location
    depends_on:
      - postgres  # Wait for the database to be ready before starting the backend

  postgres:
    image: postgres:13  # Use the official PostgreSQL image
    ports:
      - "5432:5432"  # Map the PostgreSQL port to the host machine
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data in a named volume

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:  # Define the named volume for database data
  uploads:  # Define the named volume for image uploads
