name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3. Install TypeScript globally
    - name: Install TypeScript globally
      run: npm install -g typescript

    # 4. Install Frontend Dependencies
    - name: Install Frontend Dependencies
      working-directory: ./nyush_exchange_platform_frontend  # Adjust path if needed
      run: npm install

    # 5. Install Backend Dependencies
    - name: Install Backend Dependencies
      working-directory: ./nyush_exchange_platform_server  # Adjust path if needed
      run: npm install

    # 6. Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # 8. Build Docker Images
    - name: Build Docker Images
      run: docker-compose -f docker-compose.yml build --no-cache

    # 9. Tag and Push Images to Docker Hub
    - name: Tag and Push Frontend Image
      run: |
        docker tag nyush_exchange_platform_frontend:latest minjae07206/nyush_exchange_platform_frontend:latest
        docker push minjae07206/nyush_exchange_platform_frontend:latest

    - name: Tag and Push Backend Image
      run: |
        docker tag nyush_exchange_platform_backend:latest minjae07206/nyush_exchange_platform_backend:latest
        docker push minjae07206/nyush_exchange_platform_backend:latest
