name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the 'main' branch

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Install Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3. Install TypeScript globally
    - name: Install TypeScript globally
      run: npm install -g typescript

    # 4. Install Frontend Dependencies
    - name: Install Frontend Dependencies
      working-directory: ./nyush_exchange_platform_frontend  # Adjust path if needed
      run: npm install

    # 5. Install Backend Dependencies
    - name: Install Backend Dependencies
      working-directory: ./nyush_exchange_platform_server  # Adjust path if needed
      run: npm install

    # 6. Log in to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # 8. Build Docker Images
    - name: Build Docker Images
      run: docker-compose -f docker-compose.yml build --no-cache

    # 9. Tag and Push Images to Docker Hub
    - name: Tag and Push Frontend Image
      run: |
        docker tag nyush_exchange_platform_frontend:latest minjae07206/nyush_exchange_platform_frontend:latest
        docker push minjae07206/nyush_exchange_platform_frontend:latest

    - name: Tag and Push Backend Image
      run: |
        docker tag nyush_exchange_platform_backend:latest minjae07206/nyush_exchange_platform_backend:latest
        docker push minjae07206/nyush_exchange_platform_backend:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-docker-image  # Ensures this job only runs after the `Docker Pipeline` workflow completes

    steps:
      # 1. Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v4
       # 2. Set up SSH key for secure access to the server
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Debug SSH connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ml6722@10.214.14.9 echo "SSH connection successful"

    # Step 3: Clone or pull the latest code from the repository on the server
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: whoami

      # 4. Pull both the frontend and backend Docker images from Docker Hub
      - name: Pull Docker Images
        run: |
          ssh ml6722@10.214.14.9 "docker pull minjae07206/nyush_exchange_platform_backend"
          ssh ml6722@10.214.14.9 "docker pull minjae07206/nyush_exchange_platform_frontend"
      # 5. Run all services (frontend and backend) using docker-compose
      - name: Deploy Application
        run: |
          ssh ml6722@10.214.14.9 "docker-compose -f /home/ml6722/nyush_exchange_platform/docker-compose.yml up -d"
